### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by dadaxingxing** [Algore101/Instagram-Downloader#1]
Hey Man I downloade your project from github and yesterday it was working really well and I can download reels and stuff. However today when I was running ur main.py and I click on get post button from the GUI that you created and it came back with a "KeyError: 'PostPage'". Due to this I no longer can download videos from instagram. Please respond ASAP as I really need this.

**Comment by Algore101** [comment]
Hey @dadaxingxing, thanks so much for using my project!
Could you please attach a screenshot of the error? I will attempt to recreate it and see if I can fix this issue.
